
LDLIBS=-lFoundation

LDLIBS+=-lOpenGLES_native -lUIKit_native -lCoreGraphics_native -lQuartzCore_native -lIOKit_native

OBJECTS = \
    main \
    AppDelegate \
    FooterView \

include ${MYOS_PATH}/sdk/app-makefile
